name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install # or npm ci
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
